version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    labels:
      - frontend
    schedule:
      interval: daily
    allow:
      - dependency-type: production
    # only allow security PRs to be opened.
    open-pull-requests-limit: 0

  # # Maintain dependencies for GitHub Actions
  # - package-ecosystem: "github-actions"
  #   # Workflow files stored in the default location of `.github/workflows`. (You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.)
  #   directory: "/"
  #   schedule:
  #     interval: "weekly"
  #   # only allow security PRs to be opened.
  #   open-pull-requests-limit: 0
