version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    labels:
      - frontend
    schedule:
      interval: daily
    allow:
      - dependency-type: production
    # only allow security PRs to be opened.
    open-pull-requests-limit: 0
